export const ACTIONS = {
  OPEN_ADD_ITEM_MODAL: "OPEN_ADD_ITEM_MODAL",
  CLOSE_ADD_ITEM_MODAL: "CLOSE_ADD_ITEM_MODAL",
  ADD_ITEM: "ADD_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM"
};
