export const ACTIONS = {
  OPEN_ADD_ITEM_MODAL: "OPEN_ADD_ITEM_MODAL",
  OPEN_EDIT_ITEM_MODAL: "OPEN_EDIT_ITEM_MODAL",
  CLOSE_ADD_ITEM_MODAL: "CLOSE_ADD_ITEM_MODAL",
  CHANGE_MODE: "CHANGE_MODE",
  ADD_ITEM: "ADD_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
};

export const MODES = {
  CREATE: "CREATE",
  EDIT: "EDIT",
  DELETE: "DELETE",
};
